version: '3'
services:
  db:
    build: ./db/build
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: ta_nobunaga
      MYSQL_USER: cotton
      MYSQL_PASSWORD: C0tt0nP@ss
      MYSQL_ROOT_PASSWORD: cotton
    ports:
      - "3314:3306"
    volumes:
      - ./db/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./db/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
      