version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: short_stay
      MYSQL_USER: short_stay_01
      MYSQL_PASSWORD: short_stay_01
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3314:3306"
    volumes:
      - ./db/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./db/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
      