CREATE TABLE IF NOT EXISTS GUEST_USER (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(256) UNIQUE NOT NULL,
  EMAIL VARCHAR (256) UNIQUE NOT NULL,
  PASSWORD VARCHAR (256) NOT NULL,
  INSERTED TIMESTAMP NOT NULL,
  INSERTED_BY VARCHAR (256) NOT NULL,
  UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR (256) NOT NULL,
  DELETED TIMESTAMP,
  DELETED_BY VARCHAR (256)
);

CREATE TABLE IF NOT EXISTS HOST_USER (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(256) UNIQUE NOT NULL,
  EMAIL VARCHAR (256) UNIQUE NOT NULL,
  PASSWORD VARCHAR (256) NOT NULL,
  PHONE_NO VARCHAR (256) UNIQUE NOT NULL,
  ADDRESS VARCHAR (256) NOT NULL,
  INSERTED TIMESTAMP NOT NULL,
  INSERTED_BY VARCHAR (256) NOT NULL,
  UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR (256) NOT NULL,
  DELETED TIMESTAMP,
  DELETED_BY VARCHAR (256)
);

CREATE TABLE IF NOT EXISTS HOST_USER_ATTRIBUTE (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  HOST_USER_ID BIGINT UNIQUE NOT NULL,
  VERIFY BIT NOT NULL DEFAULT FALSE,
  IS_SUPER_HOST BIT NOT NULL DEFAULT FALSE,
  APPEAL VARCHAR (1024) ,
  BIGINTRODUCTION VARCHAR (1024),
  INSERTED TIMESTAMP NOT NULL,
  INSERTED_BY VARCHAR (256) NOT NULL,
  UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR (256) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROPERTY (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  HOST_USER_ID BIGINT NOT NULL,
  NAME VARCHAR (256) NOT NULL,
  PERFECTURE VARCHAR (256) NOT NULL,
  MUNICIPALITY VARCHAR (256) NOT NULL,
  ADDRESS VARCHAR (256) NOT NULL,
  APPEAL VARCHAR (1024) ,
  TYPE VARCHAR (256) NOT NULL,
  INSERTED TIMESTAMP NOT NULL,
  INSERTED_BY VARCHAR (256) NOT NULL,
  UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR (256) NOT NULL,
  DELETED TIMESTAMP NOT NULL,
  DELETED_BY VARCHAR (256) NOT NULL
);

CREATE TABLE IF NOT EXISTS PROPERTY_IMAGE (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  PROPERTY_ID BIGINT NOT NULL,
  IMAGE_PATH VARCHAR (256) NOT NULL,
  TITLE VARCHAR (256),
  IS_MAIN BIT NOT NULL DEFAULT FALSE,
  INSERTED TIMESTAMP NOT NULL,
  INSERTED_BY VARCHAR (256) NOT NULL
);

CREATE TABLE IF NOT EXISTS  REL_PROPERTY_ATTRIBUTE (
  PROPERTY_ID BIGINT NOT NULL ,
  AMENITY_ID BIGINT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS PROPERTY_ATTRIBUTE (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR (256) NOT NULL,
  ICON_PATH VARCHAR (256),
  ORDINAL BIGINT NOT NULL,
  INSERTED TIMESTAMP NOT NULL,
  INSERTED_BY VARCHAR (256) NOT NULL
);



CREATE TABLE IF NOT EXISTS ROOM (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  PROPERTY_ID BIGINT NOT NULL,
  NAME VARCHAR (256) NOT NULL,
  INSERTED TIMESTAMP NOT NULL,
  INSERTED_BY VARCHAR (256) NOT NULL,
  UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR (256) NOT NULL,
  DELETED TIMESTAMP NOT NULL,
  DELETED_BY VARCHAR (256) NOT NULL
);

CREATE TABLE IF NOT EXISTS  REL_ROOM_AMENITY(
  ROOM_ID BIGINT NOT NULL,
  AMENITY_ID BIGINT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS AMENITY (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR (256) NOT NULL,
  ICON_PATH VARCHAR (256),
  ORDINAL BIGINT NOT NULL,
  INSERTED TIMESTAMP NOT NULL,
  INSERTED_BY VARCHAR (256) NOT NULL
);

CREATE TABLE IF NOT EXISTS ROOM_IMAGE (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ROOM_ID BIGINT NOT NULL,
  IMAGE_PATH VARCHAR (256) NOT NULL,
  TITLE VARCHAR (256),
  IS_MAIN BIT NOT NULL DEFAULT FALSE,
  INSERTED TIMESTAMP NOT NULL,
  INSERTED_BY VARCHAR (256) NOT NULL
);

CREATE TABLE IF NOT EXISTS RESERVE (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ROOM_ID BIGINT NOT NULL,
  GUEST_USER_ID BIGINT NOT NULL,
  PLAN_DATE DATE NOT NULL,
  PRICE BIGINT NOT NULL,
  PLAN_START_DATE DATE NOT NULL,
  PLAN_END_DATE DATE NOT NULL,
  INSERTED TIMESTAMP NOT NULL,
  INSERTED_BY VARCHAR (256) NOT NULL,
  UPDATED TIMESTAMP NOT NULL,
  UPDATED_BY VARCHAR (256) NOT NULL,
  CANCELD TIMESTAMP NOT NULL,
  CANCELD_BY VARCHAR (256) NOT NULL
);

CREATE TABLE IF NOT EXISTS RESERVE_DETAIL (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ROOM_ID BIGINT NOT NULL,
  PLAN_DATE DATE NOT NULL,
  PRICE BIGINT NOT NULL,
  INSERTED TIMESTAMP NOT NULL,
  INSERTED_BY VARCHAR (256) NOT NULL
);

CREATE TABLE IF NOT EXISTS CHAT_ROOM (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ROOM_ID BIGINT NOT NULL,
  GUEST_USER_ID BIGINT NOT NULL,
  INSERTED TIMESTAMP NOT NULL,
  INSERTED_BY VARCHAR (256) NOT NULL
);

CREATE TABLE IF NOT EXISTS CHAT_TALK (
  CHAT_ROOM_ID BIGINT NOT NULL,
  INSERTED TIMESTAMP NOT NULL,
  SIDE CHAR (256) NOT NULL,
  GUEST_USER_ID BIGINT NOT NULL,
  INSERTED_BY VARCHAR (256) NOT NULL,
  PRIMARY KEY (CHAT_ROOM_ID, GUEST_USER_ID, INSERTED)
);
